services:
  forward-client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app 
      - /app/node_modules
      - /app/dist
    environment:
      NODE_ENV: development
    command: sh -c "npm run run:auth && npm run dev"

  forward-client-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    command: node dist/index.js
