FROM node:20-alpine AS builder
RUN apk add --no-cache python3 py3-pip make g++ 
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

COPY . .
RUN npm run build

FROM node:20-alpine
RUN apk add --no-cache python3 py3-pip make g++
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json* ./
RUN npm install --omit=dev --no-audit --no-fund

EXPOSE 3000

CMD ["node", "dist/index.js"]
